import Router from "next/router";
import Head from "next/head";
import { useEffect } from "react";

export default function Index() {
  useEffect(() => {
    Router.push("/dashboard");
  }, []);

  return (
    <>
      <Head>
        <title>Keid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
