import Router from "next/router";
import Head from "next/head";
import { useEffect } from "react";
import { useSession } from "next-auth/react";

export default function Index() {
  const { status } = useSession();

  useEffect(() => {
    if (status === "unauthenticated") {
      Router.push("/welcome");
    }

    if (status === "authenticated") {
      Router.push("/dashboard");
    }
  }, [status]);

  return (
    <>
      <Head>
        <title>Keid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
